- hosts: all
  become: yes
  tasks:

    - name: Install nginx, hugo, git
      ansible.builtin.apt:
        update_cache: yes
        name: '{{item}}'
        state: latest
      with_items:
        - hugo
        - nginx
        - git

    - name: enable systemd unit for nginx
      ansible.builtin.systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: nginx

    - name: template nginx config
      ansible.builtin.template:
        src: snepi.space.j2
        dest: /etc/nginx/sites-available/snepi.space
        owner: root
        group: root
        mode: 0644

    - name: create symlink to sites-enabled
      ansible.builtin.file:
        state: link
        src: /etc/nginx/sites-available/snepi.space
        dest: /etc/nginx/sites-enabled/snepi.space
        owner: root
        group: root
        mode: 0644

    - name: create www-data group
      ansible.builtin.group:
        name: www-data
        state: present

    - name: create directory for site in /var/www
      ansible.builtin.file:
        state: directory
        path: /var/www/snepi.space
        mode: 0775
        group: www-data
        owner: root

    - name: clone website repo
      ansible.builtin.git:
        clone: yes
        dest: /tmp/snepi.space
        depth: 1
        repo: http://git.cloth.lan/nepi/snepi.space.git

    - name: build static site
      ansible.builtin.command:
        chdir: /tmp/snepi.space
        cmd: hugo -b http://snepi.space/

    - name: remove old site
      ansible.builtin.file:
        path: /var/www/snepi.space/
        state: absent

    - name: copy built site
      ansible.builtin.copy:
        remote_src: yes
        src: /tmp/snepi.space/public/
        dest: /var/www/snepi.space/

    - name: remove temp files
      ansible.builtin.file:
        path: /tmp/snepi.space
        state: absent

    - name: clone computercraft scripts
      ansible.builtin.git:
        clone: yes
        dest: /tmp/computercraft
        depth: 1
        repo: http://git.cloth.lan/nepi/computercraft.git

    - name: move computercraft scripts
      ansible.builtin.copy:
        remote_src: yes
        src: /tmp/computercraft
        dest: /var/www/snepi.space/

    - name: clean up computercraft
      ansible.builtin.file:
        path: /tmp/computercraft
        state: absent

    - name: reload nginx
      ansible.builtin.systemd:
        state: reloaded
        name: nginx


